# Lecture 2

## Excercise 1
- Create the array A
- Now create a new array containing only its 2nd and 4th rows
- Create a 2d array with 1 on the border and 0 on the inside

In [4]:
import numpy as np

A = np.arange(1,16).reshape(3,5).transpose()
print('A:\n', A,'\n')

B = A[[1, 3]]
print('B:\n', B,'\n')

n_row = 5
n_col = 9
C = np.ones([n_row,n_col], dtype=int)
C[1:n_row-1,1:n_col-1] = 0
print('C:\n', C,'\n')

A:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]] 

B:
 [[ 2  7 12]
 [ 4  9 14]] 

C:
 [[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]] 



# Exercise 2
Here we will read in columns of numbers from a file and create a histogram, using NumPy routines. Make sure you have the data file "sample.txt" in the same directory as this notebook. You download it from https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt.
- Use python to download a file! Check out the requests package.
- Use np.loadtxt() to read this file in.
- Next, use np.histogram() to create a histogram array. The output returns both the count and an array of edges.
- Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [6]:
import numpy as np
import requests

# Download file
url = "https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt"

with open("sample.txt", "w") as f:
    f.write((requests.get(url)).text)

# Histogram
data = np.loadtxt("sample.txt")

bins = 10
hist = np.histogram(data[:,1], bins)

for i in range(bins):
    center = (hist[1][i+1] + hist[1][i])/2
    print(f"Bin center: {center:.2f} \t Counts: {hist[0][i]}")

Bin center: -27.13 	 Counts: 3
Bin center: -20.21 	 Counts: 4
Bin center: -13.29 	 Counts: 9
Bin center: -6.37 	 Counts: 22
Bin center: 0.54 	 Counts: 22
Bin center: 7.46 	 Counts: 22
Bin center: 14.38 	 Counts: 9
Bin center: 21.30 	 Counts: 7
Bin center: 28.22 	 Counts: 1
Bin center: 35.14 	 Counts: 1
